"""empty message

Revision ID: 7321a41c4720
Revises: d8a128ce003e
Create Date: 2018-09-19 23:49:20.876829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7321a41c4720'
down_revision = 'd8a128ce003e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exh_org', schema=None) as batch_op:
        batch_op.create_unique_constraint('UC_exhibition_id_organization_id', ['exhibition_id', 'organization_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exh_org', schema=None) as batch_op:
        batch_op.drop_constraint('UC_exhibition_id_organization_id', type_='unique')

    # ### end Alembic commands ###
