"""empty message

Revision ID: 94f305218ed5
Revises: 
Create Date: 2018-08-17 18:42:19.712299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f305218ed5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pName', sa.String(length=40), nullable=True),
    sa.Column('fName', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('website', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exhibition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('startDate', sa.String(length=20), nullable=True),
    sa.Column('endDate', sa.String(length=20), nullable=True),
    sa.Column('installStart', sa.String(length=20), nullable=True),
    sa.Column('installEnd', sa.String(length=20), nullable=True),
    sa.Column('deinstallDate', sa.String(length=20), nullable=True),
    sa.Column('prm', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('website', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('park',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('park_id', sa.String(length=6), nullable=True),
    sa.Column('borough', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('cb', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_artwork',
    sa.Column('artwork_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['artwork_id'], ['artwork.id'], )
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('exhibition_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['exhibition_id'], ['exhibition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exh_art_park',
    sa.Column('exhibition_id', sa.Integer(), nullable=False),
    sa.Column('artwork_id', sa.Integer(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artwork.id'], ),
    sa.ForeignKeyConstraint(['exhibition_id'], ['exhibition.id'], ),
    sa.ForeignKeyConstraint(['park_id'], ['park.id'], ),
    sa.PrimaryKeyConstraint('exhibition_id', 'artwork_id', 'park_id')
    )
    op.create_table('exh_org',
    sa.Column('exhibition_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exhibition_id'], ['exhibition.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['org.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exh_org')
    op.drop_table('exh_art_park')
    op.drop_table('event')
    op.drop_table('artist_artwork')
    op.drop_table('park')
    op.drop_table('org')
    op.drop_table('exhibition')
    op.drop_table('artwork')
    op.drop_table('artist')
    # ### end Alembic commands ###
